//! Build scripts example
//!
//! This binary demonstrates how build scripts (build.rs) can generate code
//! and set environment variables during the build process.

// Include the generated code from build.rs
include!(concat!(env!("OUT_DIR"), "/build_info.rs"));

fn main() {
    println!("=== Build Scripts Example ===\n");

    // Use constants generated by build.rs
    println!("Build Profile: {}", BUILD_PROFILE);
    println!("Build Target: {}", BUILD_TARGET);
    println!("Build Timestamp: {}", BUILD_TIMESTAMP);
    println!();

    // Use function generated by build.rs
    println!("{}", get_build_info());
    println!();

    // Use environment variables set by build.rs
    println!("Environment variables set by build.rs:");
    println!("  BUILD_PROFILE: {}", env!("BUILD_PROFILE"));
    println!("  BUILD_TARGET: {}", env!("BUILD_TARGET"));
    println!();

    // Conditional compilation based on build.rs configuration
    #[cfg(release_build)]
    println!("This was built in release mode!");

    #[cfg(not(release_build))]
    println!("This was built in debug/dev mode!");

    println!("\n=== Done! ===");
}
